services:
  redis:
    image: redis:latest
    container_name: redis-ku
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  mysql:
    image: mysql:8.0
    container_name: mysql-ku
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword    # ubah kalau mau
      MYSQL_DATABASE: myapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  minio:
    image: minio/minio:latest
    container_name: minio-ku
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio12345678   # minimal 8 karakter
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # Console
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-ku
    environment:
      PMA_HOST: mysql                      # nama service MySQL di docker
      PMA_PORT: 3306
      PMA_ARBITRARY: 1                     # izinkan connect ke server lain kalau perlu
    ports:
      - "8080:80"                          # akses via http://localhost:8080
    restart: unless-stopped
    depends_on:
      - mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress-ku
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: appuser
      WORDPRESS_DB_PASSWORD: apppassword
      WORDPRESS_DB_NAME: myapp
    ports:
      - "8000:80" # akses via http://localhost:8000
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  redis-data:
  mysql-data:
  minio-data: